stages:
    - check
    - build

variables:
    APP_ID: "io.gitlab.Turtlico"
    BUNDLE_FILENAME: "turtlico-${CI_COMMIT_REF_NAME}"

.windows_runner:
    tags:
    - shared-windows
    - windows
    - windows-1809

flake8:
  image: "registry.fedoraproject.org/fedora:latest"
  stage: check
  script:
    - dnf install -y python3-flake8
    - flake8 --ignore E402,W503 --show-source turtlico/

flatpak:
    stage: build
    image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master"
    cache:
        key: "$CI_JOB_NAME"
        paths:
            - '.flatpak/.flatpak-builder/downloads'
            - '.flatpak/.flatpak-builder/git'
    script:
        - flatpak-builder --repo=./.flatpak/repo --force-clean _build ${APP_ID}.json
        - flatpak build-bundle ./.flatpak/repo "${BUNDLE_FILENAME}.flatpak" ${APP_ID}
    artifacts:
        name: 'Flatpak artifacts'
        expose_as: 'Get Flatpak bundle here'
        paths:
        - "${BUNDLE_FILENAME}.flatpak"
        expire_in: 14 days

windows:
    extends:
        - .windows_runner
    stage: build
    script:
        - Set-Variable -Name "time" -Value (date -Format "%H:%m")
        - echo ${time}
        - echo "started by ${GITLAB_USER_NAME}"
        - choco install msys2 -y
        - choco install innosetup -y
        - cd .\windows
        - filter replace-slash {$_ -replace "\\", "/"}
        - C:\tools\msys64\usr\bin\bash.exe -lc "$(Get-Location | replace-slash)/build.sh"
        - iscc .\build\turtlico.iss /Q /O$(Get-Location) /F"${BUNDLE_FILENAME}-setup"
    artifacts:
        name: 'Windows artifacts'
        expose_as: 'Get Windows installer here'
        paths:
        - windows/${BUNDLE_FILENAME}-setup.exe
        expire_in: 14 days
