stages:
    - test
    - build

variables:
    BUNDLE_FILENAME: "turtlico-$CI_COMMIT_REF_NAME"

flake8:
  image: "registry.fedoraproject.org/fedora:latest"
  stage: test
  script:
    - dnf install -y python3-flake8
    - flake8 --ignore E402,W503 --show-source turtlico/

include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
    stage: build
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "io.gitlab.Turtlico.json"
        FLATPAK_MODULE: "turtlico"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "io.gitlab.Turtlico"
        BUNDLE: "$BUNDLE_FILENAME.flatpak"
    tags:
    extends: .flatpak

.windows_runner:
    tags:
    - shared-windows
    - windows
    - windows-1809

windows:
    extends:
        - .windows_runner
    stage: build
    script:
        - Set-Variable -Name "time" -Value (date -Format "%H:%m")
        - echo ${time}
        - choco install msys2 -y
        - choco install innosetup -y
        - cd .\windows
        - filter replace-slash {$_ -replace "\\", "/"}
        - C:\tools\msys64\usr\bin\bash.exe -lc "$(Get-Location | replace-slash)/build.sh"
        - iscc .\build\turtlico.iss /Q /O$(Get-Location)\build /F"${BUNDLE_FILENAME}-setup"
    artifacts:
        name: 'Windows artifacts'
        expose_as: 'Get Windows installer here'
        paths:
        - windows/build/${BUNDLE_FILENAME}-setup.exe
        expire_in: 14 days
