#!/usr/bin/python3
import sys, os, tempfile
from subprocess import call

data_dir = os.path.join(os.path.dirname(os.path.dirname(sys.argv[2])), "data")
call(["glib-compile-schemas", data_dir, "--targetdir=" + sys.argv[4]])
env = os.environ.copy()
env["GSETTINGS_SCHEMA_DIR"] = sys.argv[4]

for file in os.listdir(sys.argv[2]):
	if not file.endswith('.tcp'): continue
	src = os.path.join(sys.argv[2], file)
	output = os.path.join(sys.argv[4], file)
	if os.path.isfile(output): os.remove(output)
	# Compiles	
	ret = call([sys.argv[1], '--compile=' + output, src], env=env)
	if ret != 0: exit(ret)
	# Run
	ret = call([sys.argv[3], '-m', 'py_compile', output])
	if ret != 0: exit(ret)
