name: Turtlico Web

on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write # for committing to gh-pages branch

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        target: wasm32-unknown-unknown
        override: true
        components: rust-src
    
    - name: "Install wasm-bindgen-cli"
      run: cargo +nightly install -f wasm-bindgen-cli --version 0.2.89
    
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "turtlico-web-"

    - name: "Install wasmopt / binaryen"
      run: |
        sudo apt-get update && sudo apt-get install binaryen

    - name: Build
      run: bash wasm-build.sh --build-only --profile=release

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist/release'

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: './dist/release'
        single-commit: true