name: Turtlico Web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        target: wasm32-unknown-unknown
        override: true
        components: rust-src
    - run: cargo +nightly install -f wasm-bindgen-cli --version 0.2.89
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "turtlico-web-"

    - name: Build
      run: bash wasm-build.sh --build-only

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist/dev'

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: './dist/dev'
        single-commit: true